apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-db
  template:
    metadata:
      labels:
        app: redis-db

    spec:
      containers:
      - name: redis-helper
        image: redis:latest
        ports:
        - containerPort: 6379

---


apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: python-app
spec:
  selector:
    app: python-app
  ports:
  - protocol: TCP
  - port: 6379
    targetPort: 6379

   # app.kubernetes.io/name: MyApp
 