apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python

    spec:
      containers:
      - name: python-app
        image: gcr.io/ITI-1/python-app:latest
        ports:
        - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-app
spec:
  type: LoadBalancer
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000